import React from 'react';
import { Pie } from 'react-chartjs-2';
import { renderCarbonTable, generateMapboxUrl } from '../utils/reportUtils';
import parrot from '../../img/parrot.jpg';

const CarbonReportSection = ({ results, reportRef }) => {
    // Extraction des data_fields à partir des clés du rapport
    const emissions = results["forest carbon gross emissions"]?.[0]?.data_fields || {};
    const removals = results["forest carbon gross removals"]?.[0]?.data_fields || {};
    const netFlux = results["forest carbon net flux"]?.[0]?.data_fields || {};
    const sequestration = results["full extent aboveground carbon potential sequestration"]?.[0]?.data_fields || {};

    const pieData = {
        labels: ['Carbon Gross Emissions', 'Carbon Gross Removals', 'Carbon Net Flux', 'Carbon Sequestration'],
        datasets: [{
            data: [
                emissions.gfw_forest_carbon_gross_emissions__Mg_CO2e || 0,
                removals.gfw_forest_carbon_gross_removals__Mg_CO2e || 0,
                netFlux.gfw_forest_carbon_net_flux__Mg_CO2e || 0,
                // sequestration.gfw_reforestable_extent_aboveground_carbon_potential_sequestration__Mg_C || 0
            ],
            backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#8BC34A'],
            hoverBackgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#8BC34A']
        }]
    };

    // Utilisé pour le tableau (affichage simple des principales valeurs)
    const mergedDataFields = {
        ...emissions,
        ...removals,
        ...netFlux,
    };

    const coordinates = results["forest carbon gross emissions"]?.[0]?.coordinates?.[0];

    return (
        <div
            ref={reportRef}
            className="carbon-report-a4"
        >
             {/* HEADER */}
                  <div className="report-header-wrapper" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    {/* Parrot section */}
                    <div style={{ width: '120px', height: '120px', position: 'relative', display: 'flex', alignItems: 'center' }}>
                      <div className="bg-white rounded-full ">
                        <img
                          src={parrot}
                          alt="Parrot"
                          className="w-24 h-24 rounded-full object-cover"
                        />
                      </div>
                    </div>
            
                    {/* Header titles */}
                    <div className="report-header" style={{ textAlign: 'center' }}>
                      {/* <h1>NKUSU / AGRIYIELDS REPORT</h1> */}
                      <h2>Carbon Emissions Assessment Summary</h2>
                      <p className="subtitle">
                      </p>
                    </div>
            
                    {/* Logo */}
                    <img src="/logo.jpg" alt="Logo" className="report-logo" style={{ width: '120px', height: '120px', objectFit: 'contain' }} />
                  </div>

            {/* CONTENT */}
            <div className="report-body">
                <h3>Carbon Assessment Summary</h3>
                {renderCarbonTable(mergedDataFields)}

                {/* PIE CHART */}
                <div className="report-section">
                    <h4>Carbon Emissions and Sequestration</h4>
                    <div style={{ width: '100%', maxWidth: '400px', height: '150px', margin: '0 auto' }}>
                        <Pie
                            data={pieData}
                            options={{
                                responsive: true,
                                maintainAspectRatio: false,
                                plugins: {
                                    legend: { position: 'top' },
                                    title: { display: false }
                                }
                            }}
                        />
                    </div>
                </div>

                {/* MAP */}
                {coordinates && (
                    <div className="report-section">
                        <h4>Plot Map</h4>
                        <img
                            src={generateMapboxUrl(coordinates)}
                            alt="Map"
                            className="report-map"
                        />
                    </div>
                )}
            </div>

            {/* FOOTER */}
            <div className="report-footer">
                <p>Generated by NKUSU | AGRIYIELDS</p>
            </div>
        </div>
    );
};

export default CarbonReportSection;
